#base
title: Yuxiao Feng
subtitle: An eager yound mind of tomorrow
description: Welcome to my personal space~

# avatar
avatarTitle: Yuxiao Feng
avatarDesc: quant/tech/art
# Comment
#comment:
    #duoshuo: https-nilzzzz-github-io
#Gitment
gitment:
    id: 2027b8f63f3fb6054a61
    secret: 24823b47a3f7ed2aa0ffc5f3b9f5a4670b46282e
# Social
social:
    #weibo: 7605199734
    github: yf254
    twitter: yuxiao_feng
    mail: yf254@cornell.edu

url: "https://yf254.github.io"

permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
#blog_button:
 #   title: What's New?

# Navigation buttons in the front page.s
nav:
    - {title: Projects, description: archive, url: '/archive'}  
#    - {title: Short Essays, descriptin: essay, url:'/essay'} 
 #   - {title: Posts, description: tags, url: '/tags'}      
    - {title: About Me, description: about, url: '/about'}      
    - {title: CV, description: Yuxiao Feng_Resume_0622, url: '/Resume'}    
    - {title: Github, description: github, url: 'https://github.com/yf254'}    
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
